### PR TITLE
Use RSpec fuzzy value matching for hash comparison

### LINKED ISSUE #150: Include Hash with nested matchers incorrect
I may be misunderstanding what's intended but this seems a little off to me.

In this example only `"hello" => "NOPE"` doesn't match which is correctly stated in the "Expected to include" line, but then the Diff flags `"meaning_of_life" => #<a kind of Numeric>,` as different when actually it matched fine. The `array_including` matcher worked as I expected in both places though.

```ruby
            expect({
              "hello" => "NOPE",
              "something" => "else",
              "meaning_of_life" => 42,
              "stuff" => [
                { "nuts" => "bolts" },
                { "apples" => "oranges" }
              ]
            }).to include({
              "hello" => "world",
              "meaning_of_life" => a_kind_of(Numeric),
              "stuff" => array_including(
                { "apples" => "oranges" }
              )
            })
```
```diff
         Expected { "hello" => "NOPE", "something" => "else", "meaning_of_life" => 42, "stuff" => [{ "nuts" => "bolts" }, { "apples" => "oranges" }] }
       to include ("hello" => "world")

       Diff:

       ┌ (Key) ──────────────────────────┐
       │ ‹-› in expected, not in actual  │
       │ ‹+› in actual, not in expected  │
       │ ‹ › in both expected and actual │
       └─────────────────────────────────┘

         {
       -   "hello" => "world",
       +   "hello" => "NOPE",
           "something" => "else",
       -   "meaning_of_life" => #<a kind of Numeric>,
       +   "meaning_of_life" => 42,
           "stuff" => [
             {
               "nuts" => "bolts"
             },
             {
               "apples" => "oranges"
             }
           ]
         }

```

Here I mess up the array instead, here the "Expected to include" doesn't call out the specific things, but the Diff is ok (except for the same issue as above). 

```ruby
            expect({
              "hello" => "world",
              "something" => "else",
              "meaning_of_life" => 42,
              "stuff" => [
                { "nuts" => "bolts" },
                { "apples" => "BANANAS" }
              ]
            }).to include({
              "hello" => "world",
              "meaning_of_life" => a_kind_of(Numeric),
              "stuff" => array_including(
                { "apples" => "oranges" }
              )
            })
```
```diff
         Expected { "hello" => "world", "something" => "else", "meaning_of_life" => 42, "stuff" => [{ "nuts" => "bolts" }, { "apples" => "BANANAS" }] }
       to include ("stuff" => #<a collection including ({ "apples" => "oranges" })>)

       Diff:

       ┌ (Key) ──────────────────────────┐
       │ ‹-› in expected, not in actual  │
       │ ‹+› in actual, not in expected  │
       │ ‹ › in both expected and actual │
       └─────────────────────────────────┘

         {
           "hello" => "world",
           "something" => "else",
       -   "meaning_of_life" => #<a kind of Numeric>,
       +   "meaning_of_life" => 42,
           "stuff" => [
             {
               "nuts" => "bolts"
             },
             {
               "apples" => "BANANAS"
             }
       -     {
       -       "apples" => "oranges"
       -     }
           ]
         }
```

Here I use a regex key for the array and the Diff isn't happy with that.

```ruby
            expect({
              "hello" => "NOPE",
              "something" => "else",
              "meaning_of_life" => 42,
              "stuff" => [
                { "nuts" => "bolts" },
                { "apples" => "oranges" }
              ]
            }).to include({
              "hello" => "world",
              "meaning_of_life" => a_kind_of(Numeric),
              /stuff|things/ => array_including(
                { "apples" => "oranges" }
              )
            })
```

```diff
         Expected { "hello" => "NOPE", "something" => "else", "meaning_of_life" => 42, "stuff" => [{ "nuts" => "bolts" }, { "apples" => "oranges" }] }
       to include ("hello" => "world")

       Diff:

       ┌ (Key) ──────────────────────────┐
       │ ‹-› in expected, not in actual  │
       │ ‹+› in actual, not in expected  │
       │ ‹ › in both expected and actual │
       └─────────────────────────────────┘

         {
       -   "hello" => "world",
       +   "hello" => "NOPE",
           "something" => "else",
       -   "meaning_of_life" => #<a kind of Numeric>,
       +   "meaning_of_life" => 42,
           "stuff" => [
             {
               "nuts" => "bolts"
             },
             {
               "apples" => "oranges"
             }
           ]
       -   /stuff|things/ => #<a collection including (
       -     {
       -       "apples" => "oranges"
       -     }
       -   )>
         }
```

The more nesting and matchers used the more the diff has false positives.

It's a really hard problem though and I'm very impressed with how good super_diff is in other situations, thanks for your hard work!

### PR DESCRIPTION
**Pull request by jas14**
Hello! 👋 I believe this fixes #150.

The issue seems to be that RSpec uses [fuzzy matching](https://github.com/rspec/rspec-support/blob/528d88ce6fac5f83390bf430d1c47608e9d8d29a/lib/rspec/support/fuzzy_matcher.rb#L8-L24) to [compare hashes in the "include" matcher](https://github.com/rspec/rspec-expectations/blob/1bc30dc41665ade783340d71e1d8f30bf3c9b995/lib/rspec/matchers/built_in/include.rb#L141-L147), while super_diff's current RSpec-specific HashIncluding operation tree builder uses exact equality.

I understand this likely degrades performance, but maybe it's worth it to make the diff line up with RSpec's matching logic.

Eagerly awaiting your feedback!

### CODE REVIEW

**Comment by jas14** [comment]
I believe the collection including operator tree builder has the same issue, but I'm not sure how to replace Diff::LCS's comparison operator with fuzzy matching.

File: spec/integration/rspec/include_matcher_spec.rb [hunk 1]
```diff
@@ -258,6 +258,46 @@
             in_color(color_enabled)
         end
       end
+
+      it "produces the correct failure message when fuzzy matching" do
```
Comment (mcmire) [inline spec/integration/rspec/include_matcher_spec.rb:262]: Thanks for this. Would you mind also adding a test in the `context "that is large"` section as well? (This section tests what happens when the size of the object is so large that the "Expected ... not to include ..." part of the error message has to be split up into multiple lines.)

Comment (jas14) [reply spec/integration/rspec/include_matcher_spec.rb:262]: Done!

**Review by mcmire — APPROVED** [review]

**Comment by mcmire** [comment]
Hi @jas14, thanks for the ping and sorry it took so long for me to merge this. Thanks for this PR, seems like a great solution!

**Comment by sfcgeorge** [comment]
Oh wow so much simpler than I expected, thanks! 👍
